In [3]:
# --- system setup ---
import sys
import os
sys.path.append(os.path.abspath(".."))

In [4]:
from ib_insync import Option, FuturesOption
from ibkr.Class_IBKR_IB import IBKR_IB
ibkr = IBKR_IB(port=7496)

async def start_ibkr():
    await ibkr.connect()
    print("IBKR connected:", ibkr.ib.isConnected())

await start_ibkr()

IBKR connected: True

In [5]:
underlying_conId = 751356962

In [6]:
underlying_contract = await ibkr.contract_by_conId(underlying_conId)

In [7]:
underlying_details = await ibkr.ib.reqContractDetailsAsync(underlying_contract)

In [8]:
print(underlying_details)

[ContractDetails(contract=Contract(secType='FUT', conId=751356962, symbol='BRR', lastTradeDateOrContractMonth='20260626', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6', tradingClass='BTC'), marketName='BTC', minTick=5.0, orderTypes='ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AVGCOST,BASKET,BENCHPX,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,ICE,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,PEGBENCH,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,STPPROT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', validExchanges='CME', priceMagnifier=1, underConId=296180912, longName='CME CF Bitcoin Reference Rate', contractMonth='202606', industry='', category='', subcategory='', timeZoneId='US/Central', tradingHours='20260612:1602-20260613:0200;20260613:0400-20260615:1600;20260615:1602-20260616:1600;20260616:1602-20260617:1600;20260617:1602-20260618:1600;20260618:1602-20260619:1600;20260620:CLOSED;20260619:1602-20260620:0200;20260620:0400-20260622:1600', liquidHours='20260615:0830-20260615:1515;20260616:0830-20260616:1515;20260617:0830-20260617:1515;20260618:0830-20260618:1515;20260619:0830-20260619:1515;20260620:CLOSED;20260619:1602-20260620:0200;20260620:0400-20260622:1600', evRule='', evMultiplier=0, mdSizeMultiplier=1, aggGroup=2147483647, underSymbol='BRR', underSecType='IND', marketRuleIds='380', secIdList=[], realExpirationDate='20260626', lastTradeTime='11:00:00', stockType='', minSize=1.0, sizeIncrement=1.0, suggestedSizeIncrement=1.0, cusip='', ratings='', descAppend='', bondType='', couponType='', callable=False, putable=False, coupon=0, convertible=False, maturity='', issueDate='', nextOptionDate='', nextOptionType='', nextOptionPartial=False, notes='')]

In [9]:
option_chain = await ibkr.ib.reqSecDefOptParamsAsync(underlyingSymbol=underlying_details[0].contract.symbol ,
                                                       futFopExchange=underlying_details[0].contract.exchange,
                                                       underlyingSecType=underlying_details[0].contract.secType,
                                                       underlyingConId=underlying_conId)

In [10]:
print(option_chain)

[OptionChain(exchange='CME', underlyingConId='751356962', tradingClass='BTC', multiplier='5', expirations=['20260626'], strikes=[1000.0, 5000.0, 10000.0, 17500.0, 20000.0, 22500.0, 25000.0, 27500.0, 30000.0, 32500.0, 35000.0, 37500.0, 40000.0, 42500.0, 45000.0, 47500.0, 48500.0, 49000.0, 49500.0, 50000.0, 50500.0, 51000.0, 51500.0, 52000.0, 52500.0, 53000.0, 53500.0, 54000.0, 54500.0, 55000.0, 55500.0, 56000.0, 56500.0, 57000.0, 57500.0, 58000.0, 58500.0, 59000.0, 59500.0, 60000.0, 60500.0, 61000.0, 61500.0, 62000.0, 62500.0, 63000.0, 63500.0, 64000.0, 64500.0, 65000.0, 65500.0, 66000.0, 66500.0, 67000.0, 67500.0, 68000.0, 68500.0, 69000.0, 69500.0, 70000.0, 70500.0, 71000.0, 71500.0, 72000.0, 72500.0, 73000.0, 73500.0, 74000.0, 74500.0, 75000.0, 75500.0, 76000.0, 76500.0, 77000.0, 77500.0, 78000.0, 78500.0, 79000.0, 79500.0, 80000.0, 80500.0, 81000.0, 81500.0, 82000.0, 82500.0, 83000.0, 83500.0, 84000.0, 84500.0, 85000.0, 85500.0, 86000.0, 86500.0, 87000.0, 87500.0, 88000.0, 88500.0, 89000.0, 89500.0, 90000.0, 90500.0, 91000.0, 91500.0, 92000.0, 92500.0, 93000.0, 93500.0, 94000.0, 94500.0, 95000.0, 95500.0, 96000.0, 96500.0, 97000.0, 97500.0, 98000.0, 98500.0, 99000.0, 99500.0, 100000.0, 100500.0, 101000.0, 101500.0, 102000.0, 102500.0, 103000.0, 103500.0, 104000.0, 104500.0, 105000.0, 105250.0, 105500.0, 105750.0, 106000.0, 106250.0, 106500.0, 106750.0, 107000.0, 107250.0, 107500.0, 107750.0, 108000.0, 108250.0, 108500.0, 108750.0, 109000.0, 109250.0, 109500.0, 109750.0, 110000.0, 110250.0, 110500.0, 110750.0, 111000.0, 111250.0, 111500.0, 111750.0, 112000.0, 112250.0, 112500.0, 112750.0, 113000.0, 113250.0, 113500.0, 113750.0, 114000.0, 114250.0, 114500.0, 114750.0, 115000.0, 115250.0, 115500.0, 115750.0, 116000.0, 116250.0, 116500.0, 116750.0, 117000.0, 117250.0, 117500.0, 117750.0, 118000.0, 118250.0, 118500.0, 118750.0, 119000.0, 119250.0, 119500.0, 119750.0, 120000.0, 120250.0, 120500.0, 120750.0, 121000.0, 121250.0, 121500.0, 121750.0, 122000.0, 122250.0, 122500.0, 122750.0, 123000.0, 123250.0, 123500.0, 123750.0, 124000.0, 124250.0, 124500.0, 124750.0, 125000.0, 126000.0, 127000.0, 127500.0, 128000.0, 129000.0, 130000.0, 131000.0, 132000.0, 132500.0, 133000.0, 134000.0, 135000.0, 136000.0, 137000.0, 137500.0, 138000.0, 139000.0, 140000.0, 141000.0, 142000.0, 142500.0, 143000.0, 144000.0, 145000.0, 146000.0, 147000.0, 147500.0, 148000.0, 149000.0, 150000.0, 152500.0, 155000.0, 157500.0, 160000.0, 162500.0, 165000.0, 167500.0, 170000.0, 172500.0, 175000.0, 177500.0, 180000.0, 182500.0, 185000.0, 187500.0, 190000.0, 192500.0, 195000.0, 197500.0, 200000.0, 202500.0, 205000.0, 207500.0, 210000.0, 212500.0, 215000.0, 217500.0, 220000.0, 222500.0, 225000.0, 230000.0, 235000.0, 240000.0, 245000.0, 250000.0, 255000.0, 260000.0, 265000.0, 270000.0, 275000.0, 280000.0, 285000.0, 290000.0, 295000.0, 300000.0, 305000.0, 310000.0, 315000.0, 320000.0, 325000.0, 330000.0, 335000.0, 340000.0, 345000.0, 350000.0, 355000.0, 360000.0, 365000.0, 370000.0, 375000.0, 380000.0, 385000.0, 390000.0, 400000.0, 450000.0, 500000.0, 550000.0, 600000.0])]

In [11]:
print(option_chain[0].expirations)

['20260626']

In [12]:
print(option_chain[0].strikes)

[1000.0, 5000.0, 10000.0, 17500.0, 20000.0, 22500.0, 25000.0, 27500.0, 30000.0, 32500.0, 35000.0, 37500.0, 40000.0, 42500.0, 45000.0, 47500.0, 48500.0, 49000.0, 49500.0, 50000.0, 50500.0, 51000.0, 51500.0, 52000.0, 52500.0, 53000.0, 53500.0, 54000.0, 54500.0, 55000.0, 55500.0, 56000.0, 56500.0, 57000.0, 57500.0, 58000.0, 58500.0, 59000.0, 59500.0, 60000.0, 60500.0, 61000.0, 61500.0, 62000.0, 62500.0, 63000.0, 63500.0, 64000.0, 64500.0, 65000.0, 65500.0, 66000.0, 66500.0, 67000.0, 67500.0, 68000.0, 68500.0, 69000.0, 69500.0, 70000.0, 70500.0, 71000.0, 71500.0, 72000.0, 72500.0, 73000.0, 73500.0, 74000.0, 74500.0, 75000.0, 75500.0, 76000.0, 76500.0, 77000.0, 77500.0, 78000.0, 78500.0, 79000.0, 79500.0, 80000.0, 80500.0, 81000.0, 81500.0, 82000.0, 82500.0, 83000.0, 83500.0, 84000.0, 84500.0, 85000.0, 85500.0, 86000.0, 86500.0, 87000.0, 87500.0, 88000.0, 88500.0, 89000.0, 89500.0, 90000.0, 90500.0, 91000.0, 91500.0, 92000.0, 92500.0, 93000.0, 93500.0, 94000.0, 94500.0, 95000.0, 95500.0, 96000.0, 96500.0, 97000.0, 97500.0, 98000.0, 98500.0, 99000.0, 99500.0, 100000.0, 100500.0, 101000.0, 101500.0, 102000.0, 102500.0, 103000.0, 103500.0, 104000.0, 104500.0, 105000.0, 105250.0, 105500.0, 105750.0, 106000.0, 106250.0, 106500.0, 106750.0, 107000.0, 107250.0, 107500.0, 107750.0, 108000.0, 108250.0, 108500.0, 108750.0, 109000.0, 109250.0, 109500.0, 109750.0, 110000.0, 110250.0, 110500.0, 110750.0, 111000.0, 111250.0, 111500.0, 111750.0, 112000.0, 112250.0, 112500.0, 112750.0, 113000.0, 113250.0, 113500.0, 113750.0, 114000.0, 114250.0, 114500.0, 114750.0, 115000.0, 115250.0, 115500.0, 115750.0, 116000.0, 116250.0, 116500.0, 116750.0, 117000.0, 117250.0, 117500.0, 117750.0, 118000.0, 118250.0, 118500.0, 118750.0, 119000.0, 119250.0, 119500.0, 119750.0, 120000.0, 120250.0, 120500.0, 120750.0, 121000.0, 121250.0, 121500.0, 121750.0, 122000.0, 122250.0, 122500.0, 122750.0, 123000.0, 123250.0, 123500.0, 123750.0, 124000.0, 124250.0, 124500.0, 124750.0, 125000.0, 126000.0, 127000.0, 127500.0, 128000.0, 129000.0, 130000.0, 131000.0, 132000.0, 132500.0, 133000.0, 134000.0, 135000.0, 136000.0, 137000.0, 137500.0, 138000.0, 139000.0, 140000.0, 141000.0, 142000.0, 142500.0, 143000.0, 144000.0, 145000.0, 146000.0, 147000.0, 147500.0, 148000.0, 149000.0, 150000.0, 152500.0, 155000.0, 157500.0, 160000.0, 162500.0, 165000.0, 167500.0, 170000.0, 172500.0, 175000.0, 177500.0, 180000.0, 182500.0, 185000.0, 187500.0, 190000.0, 192500.0, 195000.0, 197500.0, 200000.0, 202500.0, 205000.0, 207500.0, 210000.0, 212500.0, 215000.0, 217500.0, 220000.0, 222500.0, 225000.0, 230000.0, 235000.0, 240000.0, 245000.0, 250000.0, 255000.0, 260000.0, 265000.0, 270000.0, 275000.0, 280000.0, 285000.0, 290000.0, 295000.0, 300000.0, 305000.0, 310000.0, 315000.0, 320000.0, 325000.0, 330000.0, 335000.0, 340000.0, 345000.0, 350000.0, 355000.0, 360000.0, 365000.0, 370000.0, 375000.0, 380000.0, 385000.0, 390000.0, 400000.0, 450000.0, 500000.0, 550000.0, 600000.0]

In [13]:
option_contracts = []

for expiry in option_chain[0].expirations:
    for strike in option_chain[0].strikes:
        for right in ["C", "P"]:
            opt = FuturesOption(
                lastTradeDateOrContractMonth=expiry,
                strike=float(strike),
                right=right,
                symbol=underlying_details[0].contract.symbol,                    # from underlying future details
                exchange=underlying_details[0].contract.exchange,
                currency=underlying_details[0].contract.currency
            )
            option_contracts.append(opt)

In [14]:
qualified_options = await ibkr.ib.qualifyContractsAsync(*option_contracts)

# might take 15 seconds or more

In [15]:
print(qualified_options)

[FuturesOption(conId=751506503, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=1000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C1000', tradingClass='BTC'), FuturesOption(conId=751506545, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=1000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P1000', tradingClass='BTC'), FuturesOption(conId=751506548, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=5000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C5000', tradingClass='BTC'), FuturesOption(conId=751506518, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=5000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P5000', tradingClass='BTC'), FuturesOption(conId=751506561, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=10000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C10000', tradingClass='BTC'), FuturesOption(conId=751506558, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=10000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P10000', tradingClass='BTC'), FuturesOption(conId=852657225, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=17500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C17500', tradingClass='BTC'), FuturesOption(conId=852657015, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=17500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P17500', tradingClass='BTC'), FuturesOption(conId=764688659, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=20000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C20000', tradingClass='BTC'), FuturesOption(conId=764688665, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=20000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P20000', tradingClass='BTC'), FuturesOption(conId=852140904, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=22500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C22500', tradingClass='BTC'), FuturesOption(conId=852140804, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=22500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P22500', tradingClass='BTC'), FuturesOption(conId=816142851, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=25000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C25000', tradingClass='BTC'), FuturesOption(conId=816142691, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=25000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P25000', tradingClass='BTC'), FuturesOption(conId=852140794, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=27500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C27500', tradingClass='BTC'), FuturesOption(conId=852139758, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=27500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P27500', tradingClass='BTC'), FuturesOption(conId=764688940, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=30000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C30000', tradingClass='BTC'), FuturesOption(conId=764688562, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=30000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P30000', tradingClass='BTC'), FuturesOption(conId=852141169, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=32500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C32500', tradingClass='BTC'), FuturesOption(conId=852139907, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=32500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P32500', tradingClass='BTC'), FuturesOption(conId=816141980, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=35000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C35000', tradingClass='BTC'), FuturesOption(conId=816141989, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=35000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P35000', tradingClass='BTC'), FuturesOption(conId=852141065, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=37500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C37500', tradingClass='BTC'), FuturesOption(conId=852140691, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=37500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P37500', tradingClass='BTC'), FuturesOption(conId=764688610, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=40000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C40000', tradingClass='BTC'), FuturesOption(conId=764688653, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=40000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P40000', tradingClass='BTC'), FuturesOption(conId=852140811, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=42500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C42500', tradingClass='BTC'), FuturesOption(conId=852140027, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=42500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P42500', tradingClass='BTC'), FuturesOption(conId=816141984, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=45000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C45000', tradingClass='BTC'), FuturesOption(conId=816142687, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=45000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P45000', tradingClass='BTC'), FuturesOption(conId=852140789, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=47500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C47500', tradingClass='BTC'), FuturesOption(conId=852140039, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=47500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P47500', tradingClass='BTC'), FuturesOption(conId=890139541, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=48500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C48500', tradingClass='BTC'), FuturesOption(conId=890139669, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=48500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P48500', tradingClass='BTC'), FuturesOption(conId=852657016, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=49000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C49000', tradingClass='BTC'), FuturesOption(conId=852658245, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=49000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P49000', tradingClass='BTC'), FuturesOption(conId=852658257, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=49500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C49500', tradingClass='BTC'), FuturesOption(conId=852657010, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=49500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P49500', tradingClass='BTC'), FuturesOption(conId=751506571, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=50000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C50000', tradingClass='BTC'), FuturesOption(conId=751506528, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=50000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P50000', tradingClass='BTC'), FuturesOption(conId=852655475, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=50500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C50500', tradingClass='BTC'), FuturesOption(conId=852655415, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=50500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P50500', tradingClass='BTC'), FuturesOption(conId=852655512, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=51000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C51000', tradingClass='BTC'), FuturesOption(conId=852656546, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=51000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P51000', tradingClass='BTC'), FuturesOption(conId=852656551, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=51500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C51500', tradingClass='BTC'), FuturesOption(conId=852656792, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=51500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P51500', tradingClass='BTC'), FuturesOption(conId=852658237, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=52000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C52000', tradingClass='BTC'), FuturesOption(conId=852656365, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=52000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P52000', tradingClass='BTC'), FuturesOption(conId=852140360, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=52500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C52500', tradingClass='BTC'), FuturesOption(conId=852140045, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=52500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P52500', tradingClass='BTC'), FuturesOption(conId=852656371, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=53000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C53000', tradingClass='BTC'), FuturesOption(conId=852658415, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=53000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P53000', tradingClass='BTC'), FuturesOption(conId=852655478, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=53500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C53500', tradingClass='BTC'), FuturesOption(conId=852655416, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=53500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P53500', tradingClass='BTC'), FuturesOption(conId=852655257, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=54000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C54000', tradingClass='BTC'), FuturesOption(conId=852658240, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=54000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P54000', tradingClass='BTC'), FuturesOption(conId=852655308, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=54500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C54500', tradingClass='BTC'), FuturesOption(conId=852656542, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=54500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P54500', tradingClass='BTC'), FuturesOption(conId=816142854, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=55000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C55000', tradingClass='BTC'), FuturesOption(conId=816142136, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=55000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P55000', tradingClass='BTC'), FuturesOption(conId=852655421, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=55500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C55500', tradingClass='BTC'), FuturesOption(conId=852658250, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=55500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P55500', tradingClass='BTC'), FuturesOption(conId=852655481, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=56000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C56000', tradingClass='BTC'), FuturesOption(conId=852658255, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=56000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P56000', tradingClass='BTC'), FuturesOption(conId=852139879, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=56500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C56500', tradingClass='BTC'), FuturesOption(conId=852140040, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=56500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P56500', tradingClass='BTC'), FuturesOption(conId=852141759, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=57000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C57000', tradingClass='BTC'), FuturesOption(conId=852140915, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=57000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P57000', tradingClass='BTC'), FuturesOption(conId=852140821, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=57500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C57500', tradingClass='BTC'), FuturesOption(conId=852139760, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=57500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P57500', tradingClass='BTC'), FuturesOption(conId=852139880, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=58000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C58000', tradingClass='BTC'), FuturesOption(conId=852141034, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=58000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P58000', tradingClass='BTC'), FuturesOption(conId=852140060, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=58500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C58500', tradingClass='BTC'), FuturesOption(conId=852140918, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=58500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P58500', tradingClass='BTC'), FuturesOption(conId=851822253, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=59000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C59000', tradingClass='BTC'), FuturesOption(conId=851822242, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=59000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P59000', tradingClass='BTC'), FuturesOption(conId=852140679, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=59500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C59500', tradingClass='BTC'), FuturesOption(conId=852139891, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=59500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P59500', tradingClass='BTC'), FuturesOption(conId=764688682, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=60000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C60000', tradingClass='BTC'), FuturesOption(conId=764688311, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=60000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P60000', tradingClass='BTC'), FuturesOption(conId=852140554, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=60500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C60500', tradingClass='BTC'), FuturesOption(conId=852139741, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=60500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P60500', tradingClass='BTC'), FuturesOption(conId=851535229, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=61000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C61000', tradingClass='BTC'), FuturesOption(conId=851535161, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=61000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P61000', tradingClass='BTC'), FuturesOption(conId=852140680, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=61500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C61500', tradingClass='BTC'), FuturesOption(conId=852140674, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=61500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P61500', tradingClass='BTC'), FuturesOption(conId=851535320, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=62000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C62000', tradingClass='BTC'), FuturesOption(conId=851535274, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=62000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P62000', tradingClass='BTC'), FuturesOption(conId=852140685, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=62500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C62500', tradingClass='BTC'), FuturesOption(conId=852140934, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=62500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P62500', tradingClass='BTC'), FuturesOption(conId=851535234, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=63000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C63000', tradingClass='BTC'), FuturesOption(conId=851535279, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=63000.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P63000', tradingClass='BTC'), FuturesOption(conId=852139894, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=63500.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C63500', tradingClass='BTC'), FuturesOption(conId=852140384, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=63500.0, right='P', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 P63500', tradingClass='BTC'), FuturesOption(conId=851535723, symbol='BRR', lastTradeDateOrContractMonth='20260626', strike=64000.0, right='C', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6 C64000', tradingClass='BTC'), FuturesOption(conId=851535239, symbol='BRR', lastTradeDat

In [21]:
rows = []

for opt in qualified_options:
    rows.append({
        "expiry": opt.lastTradeDateOrContractMonth,
        "strike": opt.strike,
        "right": opt.right,
        "option_conId": opt.conId,
        #"symbol": opt.symbol,
        #"localSymbol": opt.localSymbol,
        #"exchange": opt.exchange,
        #"currency": opt.currency,
        #"tradingClass": opt.tradingClass,
        #"multiplier": opt.multiplier
    })

In [26]:
import pandas as pd
df_options = pd.DataFrame(rows)

df_options.insert(0, "underlying_conId", underlying_conId)

df_options

     underlying_conId    expiry    strike right  option_conId
0           751356962  20260626    1000.0     C     751506503
1           751356962  20260626    1000.0     P     751506545
2           751356962  20260626    5000.0     C     751506548
3           751356962  20260626    5000.0     P     751506518
4           751356962  20260626   10000.0     C     751506561
..                ...       ...       ...   ...           ...
611         751356962  20260626  500000.0     P     799038220
612         751356962  20260626  550000.0     C     799038217
613         751356962  20260626  550000.0     P     799038241
614         751356962  20260626  600000.0     C     799038226
615         751356962  20260626  600000.0     P     799038244

[616 rows x 5 columns]

In [27]:
call_df = df_options[df_options["right"] == "C"]
put_df = df_options[df_options["right"] == "P"]

options_df = pd.merge(call_df, put_df, on=['underlying_conId', "expiry", "strike"], suffixes=("_call", "_put"))
options_df.drop(columns=["right_call", "right_put"], inplace=True)

options_df

     underlying_conId    expiry    strike  option_conId_call  option_conId_put
0           751356962  20260626    1000.0          751506503         751506545
1           751356962  20260626    5000.0          751506548         751506518
2           751356962  20260626   10000.0          751506561         751506558
3           751356962  20260626   17500.0          852657225         852657015
4           751356962  20260626   20000.0          764688659         764688665
..                ...       ...       ...                ...               ...
303         751356962  20260626  400000.0          751506509         751506543
304         751356962  20260626  450000.0          799038251         799038232
305         751356962  20260626  500000.0          799038237         799038220
306         751356962  20260626  550000.0          799038217         799038241
307         751356962  20260626  600000.0          799038226         799038244

[308 rows x 5 columns]

In [28]:
options_df.to_csv("options_conIds.csv", index=False)